apiVersion: v1
kind: PersistentVolume
metadata:
  name: status-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/app/status"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-status-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi