apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcco_app
  labels:
    app: mcco_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcco_app
  template:
    metadata:
      labels:
        app: mcco_app
    spec:
      containers:
      - name: mcco_app
        image: mcco_connected:latest
        envFrom:
        - configMapRef:
            name: mcco-app-config
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: app-status
          mountPath: /app/status
        
      volumes:
      - name: app-logs
        persistentVolumeClaim:
          claimName: app-logs-pvc
      - name: app-status
        persistentVolumeClaim:
          claimName: app-status-pvc