apiVersion: v1
kind: Service
metadata:
  name: mcco-app_service
  labels:
    app: mcco-app
spec:
  type: ClusterIP
  selector:
    app: mcco-app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001