apiVersion: v1
kind: ConfigMap
metadata:
  name: mcco-app-config
  namespace: minecraft-development
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  LOG_PATH: "/app/logs/"
  STATUS_FILE: "/app/status/mcco_post_status.json"
  PORT: "5000"
  