apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcco-ingress
  annotations:
    spec.ingressClassName: "traefik"
    traefik.frontend.passHostHeader: "true"
    treafik.backend.loadbalancer.stickiness: "true"
spec:
  rules:
  - host: mcco.gbe.ovh
    http:
      paths:
        - path: /mcco
          pathType: Prefix
          backend:
            service:
              name: mcco-app-service
              port:
                number: 5000