apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mcco-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.passHostHeader: "true"
    treafik.backend.loadbalancer.stickiness: "true"
spec:
  entryPoints:
  - http
  routes:
  - kind: Rule
    match: Host(`minecraft-server.com`) && PathPrefix(`/mcco`)
    services:
    - name: mcco-app-service
      port: 5000